apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: data-lake
spec:
  schedule: "*/1 * * * *" #Minuto (0/59) | Hora (0/23) | Dia (1/31) | Mês (1/12)| Dia da semana (0/7) | 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dlake
            image: dlake11g:2 #andressaidalgof/dlake
            # args:
            # - "python"
            # - "/home/ProcessoIngestao.py"
          volumes:
          - name: html
            gitRepo:
              repository: https://github.com/luksa/kubia-website-example.git
              #repository: https://bitbucket.org/compassouoldiveo/sistemas-internos.datalake.aws.git
              revision: Docker
              directory: .  
          restartPolicy: OnFailure