--- 
apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: data-lake-cron
  #namespace: $NAMESPACE
spec:
  schedule: "*/1 * * * *"
  jobTemplate: 
    spec: 
      template: 
        spec:
          containers: 
            - name: git-sync
              image: "k8s.gcr.io/git-sync:v3.1.6"
              volumeMounts: 
                - mountPath: /home #era home
                  name: data-git
              env: 
                - name: GIT_SYNC_REPO
                  value: "https://bitbucket.org/compassouoldiveo/sistemas-internos.datalake.aws"
                - name: GIT_SYNC_DEST
                  value: home
                - name: GIT_SYNC_BRANCH
                  value: Docker
                - name: GIT_SYNC_ROOT
                  value: home # era /home
                - name: GIT_SYNC_USERNAME
                  valueFrom: 
                    secretKeyRef: 
                      key: GIT_USERNAME
                      name: git-credential
                - name: GIT_SYNC_PASSWORD
                  valueFrom: 
                    secretKeyRef: 
                      key: GIT_PASSWORD
                      name: git-credential
            - name: data-lake
              image: "andressaidalgof/dlake:V2" #809962635191.dkr.ecr.us-east-1.amazonaws.com/compasso/sistemas-internos.mobile.app:4-06-2020-2007-12 #$IMAGE #"andressaidalgof/dlake:V2"
              volumeMounts: 
                - mountPath: home/ 
                  name: data-git
              #command: ["printenv"]
              command: ["python"]
              #args: ["/home/test.py"]    
              env: 
                - name: USERNAME
                  valueFrom: 
                    secretKeyRef:
                      key: user
                      name: dev-data-lake-credential-secret
                - name: DB_PASSWORD
                  valueFrom: 
                    secretKeyRef: 
                      key: pass
                      name: dev-data-lake-credential-secret
              envFrom: 
                - configMapRef: 
                    name: dev-data-lake-config       
          restartPolicy: OnFailure
          volumes: 
            - emptyDir: {}
              name: data-git