apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-git-sync
  name: php-git-sync-dev
  namespace: compasso-rh-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-git-sync
  template:
    metadata:
      labels:
        app: php-git-sync
    spec:
      containers:
      - command:
        - sh
        - -c
        - |
          docker-entrypoint.sh;
        image: php:7.2-apache
        imagePullPolicy: IfNotPresent
        name: php
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/bin/docker-entrypoint.sh
          name: docker-entrypoint
          subPath: docker-entrypoint.sh
        - mountPath: /var/www/html
          name: shared-stage
        - mountPath: /var/www/html/db/conexao.php
          name: dbconfig
          subPath: conexao.php
      dnsPolicy: ClusterFirst
      initContainers:
      - env:
        - name: GIT_SYNC_REPO
          value: https://bitbucket.org/compassouoldiveo/sistemas-internos.rh.admissao
        - name: GIT_SYNC_BRANCH
          value: develop
        - name: GIT_SYNC_DEST
          value: git-sync
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        - name: GIT_SYNC_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: git-intranet
        - name: GIT_SYNC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: git-intranet
        - name: HOME
          value: /tmp
        image: k8s.gcr.io/git-sync-amd64:v2.0.6
        imagePullPolicy: Always
        name: git-sync
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /git
          name: shared-data-git
      - command:
        - sh
        - -c
        - |
          sleep 10; cp -ar /git/git-sync/* /stage/;
        image: busybox
        imagePullPolicy: Always
        name: copy-files
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /git
          name: shared-data-git
        - mountPath: /stage
          name: shared-stage
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 356
          name: docker-entrypoint
        name: docker-entrypoint
      - emptyDir: {}
        name: shared-stage
      - emptyDir: {}
        name: shared-data-git
      - configMap:
          defaultMode: 420
          name: db-config
        name: dbconfig
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-06T14:20:26Z"
    lastUpdateTime: "2020-03-06T14:20:51Z"
    message: ReplicaSet "php-git-sync-dev-cdb786d4d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-05-20T03:36:34Z"
    lastUpdateTime: "2020-05-20T03:36:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1