--- 
apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: data-lake-cron
  #namespace: $NAMESPACE
spec:
  schedule: "*/1 * * * *"
  jobTemplate: 
    spec: 
      template: 
        spec:
          containers:
            - name: data-lake
              image: "andressaidalgof/dlake:V2" #809962635191.dkr.ecr.us-east-1.amazonaws.com/compasso/sistemas-internos.mobile.app:4-06-2020-2007-12 #$IMAGE #"andressaidalgof/dlake:V2"
              command: 
               - printenv
              # command: ["python"]
              # args: ["/home/test.py"]    
                - name: shared-stage
                  mountPath: /home               
              env: 
                - name: USERNAME
                  valueFrom: 
                    secretKeyRef:
                      key: user
                      name: dev-data-lake-credential-secret
                - name: PASSWORD
                  valueFrom: 
                    secretKeyRef: 
                      key: pass
                      name: dev-data-lake-credential-secret
              envFrom: 
                - configMapRef: 
                    name: dev-data-lake-config       
          initContainers: 
            - name: git-sync
              image: k8s.gcr.io/git-sync-amd64:v2.0.6 #"k8s.gcr.io/git-sync:v3.1.6"
              command:
                - sh
                - -c
                - >
                  sleep 1000;
              volumeMounts: 
                - name: data-git
                  mountPath: /git
              env: 
                - name: GIT_SYNC_REPO
                  value: "https://bitbucket.org/compassouoldiveo/sistemas-internos.datalake.aws"
                - name: GIT_SYNC_DEST
                  value: home
                - name: GIT_SYNC_BRANCH
                  value: Docker
                - name: GIT_SYNC_ONE_TIME
                  value: "true"  
                - name: GIT_SYNC_USERNAME
                  valueFrom: 
                    secretKeyRef: 
                      key: GIT_USERNAME
                      name: git-credential
                - name: GIT_SYNC_PASSWORD
                  valueFrom: 
                    secretKeyRef: 
                      key: GIT_PASSWORD
                      name: git-credential
                - name: HOME
                  value: /tmp
            - name: copy-files
              image: busybox
              securityContext:
                privileged: true
              command:
                - sh
                - -c
                - >
                  sleep 1000;
                  cp -ar /git/git-sync/* /home/;
              volumeMounts:
              - name: data-git
                mountPath: /git
            
          restartPolicy: OnFailure
          volumes: 
            - emptyDir: {}
              name: data-git
            - emptyDir: {}
              name: shared-stage