apiVersion: v1
kind: Pod
metadata:
  name: itiro
spec:
  containers:
  - name: mycontainer
    image: nginx
    volumeMounts:
      - mountPath: /volumemount
        name: myvol
  volumes:
  - name: myvol
    persistentVolumeClaim: 
      claimName: myvol1
